# Generated by Django 3.2 on 2022-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling_appts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
